### ISSUE TITLE
Remove figgy-pudding dependency

### ISSUE THREAD

**Issue by mikemimik** [npm/npm-pick-manifest#6]
### References
- https://github.com/npm/statusboard/issues/66
- Closes: https://github.com/npm/npm-pick-manifest/pull/5

##### Branches
- ~https://github.com/npm/npm-pick-manifest/tree/isaacs/de-fig~
- https://github.com/npm/npm-pick-manifest/tree/mikemimik/feature/remove-figgy-dep (rebased above branch)

**Comment by isaacs** [comment]
Fixed by #5.
